quarkiverse/quarkus-pact

- .gitignore
- quarkus-pact-provider/README.md
- quarkus-pact-provider/deployment/pom.xml
- quarkus-pact-provider/integration-tests/pom.xml
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/README.md
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/pom.xml
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/src/test/java/io/quarkiverse/pact/devmodetest/farm/DummyAlpacaTest.java
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/src/test/java/io/quarkiverse/pact/devmodetest/farm/FarmContractTest.java
- quarkus-pact-provider/runtime/pom.xml
- quarkus-pact-provider/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Resolves #11 
This PR does the following:
- Enable the integration tests, which had been failing
- Use filtered versions rather than hardcoded versions in the integration project pom
- Add a dummy test to help problem diagnosis in the integration tests
- Make the integration tests work, by … 
- Setting the scope of the extension dependency to not-test; this isn’t great, but may be hard to fix. 
- Making pact work in dev mode
The changes to make pact work in dev mode are 
- Add the quarkus kotlin extension as a dependency to the extension
- Set a bunch of libraries used by pact to be parent first, to work around `NoClassDefFoundError` issues. I’m a bit concerned about the implications of this change, since parent-firstness tends to spread virally through a codebase via transitive …
> Make pact tests work in dev mode

- .github/project.yml
- quarkus-pact-provider/docs/modules/ROOT/pages/includes/attributes.adoc
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- Enables provider tests to run in dev mode 
- The extension dependency must *not* have `test` scope in the pom.xml when using dev mode
> Release 0.1

- .github/workflows/release.yml
It may be responsible for the failure of the recent 0.2 release: https://github.com/quarkiverse/quarkus-pact/actions/runs/3885280542
> Revert "Adjust release.yml for multi-extension scenario"

- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/TestModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/resources-filtered/projects/happy-knitter/pom.xml
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/TtestModeContractTestIT.java
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/pom.xml
Related to #28. 
Since `quarkus:test` and `quarkus:dev` can behave differently, I've added some new tests for running this way. Test mode now works properly with `test` scope, but dev mode does not yet. 
I wasn't sure which workaround to leave in the codebase, but in the end I switched to `test` scope and therefore disabled the dev mode tests. 
This change requires https://github.com/quarkusio/quarkus/pull/30281 and https://github.com/quarkusio/quarkus/pull/30238, so it can't be merged until Quarkus 2.16.
> Add tests for what happens with `quarkus:test`

- .github/workflows/quarkus-snapshot.yaml
I don't think the CI for this PR will show much, since it's a different build run on an automated schedule, but we can confirm it doesn't break things, at least.
> Correct bad link in ecosystem ci setup.

- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/TheTestModeContractTestIT.java
Interestingly, the class name is *not* a typo, it's a workaround for a very subtle bug. If the test name starts with Test, it causes other tests to fail with missing resource issues. However, with the name as `Ttest`, I'm likely to try to fix the name every few weeks, when I forget why the name is the way it is, and don't read the comment.
> Fix typo in class name

- pom.xml
- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/TestModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/resources-filtered/projects/happy-knitter/src/main/java/io/quarkiverse/pact/testapp/AlpacaService.java
- quarkus-pact-consumer/integration-tests/src/test/resources-filtered/projects/happy-knitter/src/main/java/io/quarkiverse/pact/testapp/Knitter.java
- quarkus-pact-consumer/integration-tests/src/test/resources-filtered/projects/happy-knitter/src/test/java/io/quarkiverse/pact/devmodetest/farm/FarmWithInjectionConsumerTest.java
- quarkus-pact-consumer/runtime/pom.xml
- quarkus-pact-provider/deployment/src/test/java/io/quarkiverse/pact/testapp/farm/alpaca/AlpacaResource.java
- quarkus-pact-provider/integration-tests/src/main/java/io/quarkiverse/pact/testapp/farm/alpaca/IntegrationAlpacaResource.java
- quarkus-pact-provider/integration-tests/src/test/resources-filtered/projects/happy-farm/src/main/java/io/quarkiverse/pact/testapp/IntegrationDevModeAlpacaResource.java
- quarkus-pact-provider/runtime/pom.xml
Quarkus 3 brings two major changes - the javax/jakarta namespace change, and a change to classloading. Quarkus 2 core defined many pact modules to be parentfirst. In Quarkus 3, that will be done by this extension. The Quarkus 3 kotlin extension also stopped loading kotlin parent first.
*Consumer*
I was able to remove all the parent-first dependencies for the consumer. 
*Provider*
For the provider, oddly, I had it working with a single parent-first dependency (one pact library) in December, but now I needed the full set. I think that's because of the reversion of https://github.com/quarkusio/quarkus/pull/29785 between when I first did the work and now. 
I will continue working to see if I can reduce it down to a minimal set, or having both extensions in the same project will be a problem. …
> Basic Quarkus 3 toleration

- cross-extension-integration-tests/pom.xml
The ecosystem builds are failing with the following error:
```
2023-03-13T06:15:18.9350281Z [ERROR] [ERROR] Some problems were encountered while processing the POMs:
2023-03-13T06:15:18.9352044Z [WARNING] 'parent.relativePath' of POM io.quarkiverse.pact:cross-extension-integration-tests:0.3-SNAPSHOT (/home/runner/work/quarkus-pact/quarkus-pact/current-repo/cross-extension-integration-tests/pom.xml) points at io.quarkiverse.pact:quarkus-pact-parent instead of io.quarkiverse.pact:quarkus-pact-provider-parent, please verify your project structure @ line 5, column 11
2023-03-13T06:15:18.9354496Z [FATAL] Non-resolvable parent POM for io.quarkiverse.pact:cross-extension-integration-tests:0.3-SNAPSHOT: Could not find artifact io.quarkiverse.pact:quarkus-pact-provider-parent:pom:0.3-SNAPSHOT in …
```
> Fix incorrect name in cross-extension tests, caught only by CI ecosystem

- cross-extension-integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
These were fixed by https://github.com/quarkusio/quarkus/pull/30383, but I missed re-enabling the tests. 
With this, I think we can say that #28 is sorted out. Both extensions run with `test` scope with both `quarkus:dev` and `quarkus:test`.
> Re-enable tests 

- .github/workflows/build.yml
- .github/workflows/quarkus-snapshot.yaml
Builds have the following warning:
[Build on ubuntu-latest](https://github.com/quarkiverse/quarkus-pact/actions/runs/4789411531/jobs/8517252234)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
https://github.com/actions/checkout/issues/1047 has a bit more information about the warning. The simplest suggestion is to update to v3 of the actions.
> Update actions to more recent versions

- quarkus-pact-provider/runtime/pom.xml
Resolves #57. 
When run without something like 
```
export PACT_DO_NOT_TRACK=true
```
we get a stack trace from the pact-provider extension. The classes which are loaded parentfirst try to find the Apache Request class, but can't. I'm reluctant to add more classes to the parent first list in case it interferes with other libraries, and this stack trace is apparently harmless ... but it is noisy.
Hopefully once we have more control over the JUnit classloader we can remove everything from the parent-first section.
> Include httpclient5-fluent in what we load parent-first

- README.md
https://github.com/quarkiverse/quarkus-pact/issues/28 is fix and LATEST (that is 1.0.0.Final) already contains fixed as it is based on 3.0.1.Final.
> Dependencies in README should have test scope by default

- quarkus-pact-provider/runtime/pom.xml
fixes #136 
With the latest snapshot of Quarkus, the tests fail with `ClassNotFoundException: groovy.lang.Closure` due to https://github.com/quarkusio/quarkus/pull/34447
* Re-add Groovy as parent-first artifact
The tests pass again
```
mvn clean install -Dnative
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus - Pact - Parent 1.1-SNAPSHOT:
[INFO] 
[INFO] Quarkus - Pact - Parent ............................ SUCCESS [  0.991 s]
[INFO] Quarkus Pact Provider - Parent ..................... SUCCESS [  0.021 s]
[INFO] Quarkus Pact Provider - Runtime .................... SUCCESS [  1.560 s]
[INFO] Quarkus Pact Provider - Deployment ................. SUCCESS [ 29.659 s]
[INFO] Quarkus Pact Provider - Integration Tests .......... …
```
> Ref #136: Re-add Groovy as parent-first artifact

- cross-extension-integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
`DevModeTestUtils` should be replaced with an instance of `DevModeClient`. The parent classes have an instance we can use.
> Tidy deprecation warning for `DevModeTestUtils`

- docs/modules/ROOT/pages/includes/attributes.adoc
- pom.xml
It's not possible to go up to 4.5.8 (or higher) without resolving the following issues, but now that the build is running with Java 17, 4.5.7 is a clean transition. 
```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/input/UnsynchronizedByteArrayInputStream
at au.com.dius.pact.core.model.ContentType.<clinit>(ContentType.kt:152)
at au.com.dius.pact.core.model.Request$Companion.fromJson(Request.kt:160)
at au.com.dius.pact.core.model.DefaultPactReader.extractRequest(PactReader.kt:327)
at au.com.dius.pact.core.model.DefaultPactReader$loadV2Pact$interactions$1.invoke(PactReader.kt:283)
at au.com.dius.pact.core.model.DefaultPactReader$loadV2Pact$interactions$1.invoke(PactReader.kt:282)
at au.com.dius.pact.core.support.json.JsonValueKt.map(JsonValue.kt:335)
at …
```
> Minor bump in Pact version

- docs/modules/ROOT/pages/includes/attributes.adoc
- pom.xml
- quarkus-pact-provider/runtime/pom.xml
We can't just bump the version number for Pact 4.5.7 and greater, because they bring in some new dependencies that need to be marked parent first.
> Update to Pact 4.6.6

- .github/dependabot.yml
Not testable in the PR, sadly.
> Get dependabot to manage versions of actions

- .github/dependabot.yml
- cross-extension-integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
Somewhere between Quarkus 3.11 and 3.12 [the ecosystem CI started failing](https://github.com/quarkiverse/quarkiverse/issues/94). The root cause was not obvious, but I believe it is caused by OOMs somewhere, which do not make it to visible stack traces. 
The pragmatic fix for pact is to allow more memory. The Quarkus issue is (sort of) tracked by https://github.com/quarkusio/quarkus/issues/38814 and https://github.com/quarkusio/quarkus/issues/41156.
> Fix failures in ecosystem CI, caused by insufficient memory

- cross-extension-integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- cross-extension-integration-tests/src/test/java/io/quarkiverse/pact/it/TheTestModeContractTestIT.java
- cross-extension-integration-tests/src/test/resources-filtered/projects/happy-everyone-all-together/src/test/java/io/quarkiverse/pact/devmodetest/consumer/knitter/FarmWithInjectionConsumerTest.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/TestModeContractTestIT.java
- quarkus-pact-consumer/integration-tests/src/test/resources-filtered/projects/happy-knitter/src/test/java/io/quarkiverse/pact/devmodetest/farm/FarmWithInjectionConsumerTest.java
Fixes #73, by confirming that parameter injection now works properly with Quarkus 3.13.0.
> Enable test for injection

- docs/pom.xml
- quarkus-pact-consumer/pom.xml
- quarkus-pact-provider/pom.xml
Following instructions here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#for-extension-developers
> Update config doc generation to 3.14 style

- pom.xml
- quarkus-pact-consumer/pom.xml
- quarkus-pact-provider/pom.xml
See discussion in https://github.com/quarkiverse/quarkus-pact/pull/236#discussion_r1818801242
@gsmet, thank you for your help. Does this look better? 
I think I now understand the intention of the changes :) 
(... although I still don't understand how my previous version built cleanly.)
> Correct docs generation
